### ISSUE TITLE
errro low heap memory

### ISSUE THREAD

**Issue by mkscala** [jmreicha/elk-docker#4]
My compose file:
version: '2'
services:
    elasticsearch:
      image: elasticsearch:5
      command: elasticsearch
      environment:
        # This helps ES out with memory usage
        - ES_JAVA_OPTS=-Xmx1g -Xms1g
      volumes:
        # Persist elasticsearch data to a volume
        - elasticsearch:/usr/share/elasticsearch/data
        # Extra ES configuration options
        - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "9200:9200"
        - "9300:9300"

```
kibana:
  image: kibana:5
  environment:
    # Point Kibana to the elasticsearch container
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
    - "5601:5601"
  links:
    - elasticsearch
```

volumes:
  elasticsearch:

/docker-elk5$ docker-compose up
Starting dockerelk5_elasticsearch_1
Starting dockerelk5_kibana_1
Attaching to dockerelk5_elasticsearch_1, dockerelk5_kibana_1
elasticsearch_1  | [2016-09-15 21:16:04,047][INFO ][node                     ] [logstash] initializing ...
elasticsearch_1  | [2016-09-15 21:16:04,148][INFO ][env                      ] [logstash] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda)]], net usable_space [72.8gb], net total_space [117.9gb], spins? [possibly], types [ext4]
elasticsearch_1  | [2016-09-15 21:16:04,148][INFO ][env                      ] [logstash] heap size [989.8mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2016-09-15 21:16:04,152][INFO ][node                     ] [logstash] version[5.0.0-alpha5], pid[1], build[d327dd4/2016-08-04T08:59:39.568Z], OS[Linux/3.13.0-24-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_102/25.102-b14]
elasticsearch_1  | [2016-09-15 21:16:05,093][INFO ][io.netty.util.internal.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [ingest-common]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [lang-expression]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [lang-groovy]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [lang-mustache]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [lang-painless]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [percolator]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [reindex]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [transport-netty3]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] loaded module [transport-netty4]
elasticsearch_1  | [2016-09-15 21:16:05,219][INFO ][plugins                  ] [logstash] no plugins loaded
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:kibana@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:elasticsearch@5.0.0-alpha5","info"],"pid":18,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:console@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:kbn_doc_views@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:kbn_vislib_vis_types@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:markdown_vis@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:metric_vis@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:spy_modes@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["error","elasticsearch"],"pid":18,"message":"Request error, retrying\nHEAD http://elasticsearch:9200/ => connect ECONNREFUSED 172.28.0.2:9200"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:status_page@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:table_vis@5.0.0-alpha5","info"],"pid":18,"state":"green","message":"Status changed from uninitialized to green - Ready","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["listening","info"],"pid":18,"message":"Server running at http://0.0.0.0:5601"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","ui settings","info"],"pid":18,"state":"yellow","message":"Status changed from uninitialized to yellow - Elasticsearch plugin is yellow","prevState":"uninitialized","prevMsg":"uninitialized"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["warning","elasticsearch"],"pid":18,"message":"Unable to revive connection: http://elasticsearch:9200/"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["warning","elasticsearch"],"pid":18,"message":"No living connections"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","plugin:elasticsearch@5.0.0-alpha5","error"],"pid":18,"state":"red","message":"Status changed from yellow to red - Unable to connect to Elasticsearch at http://elasticsearch:9200.","prevState":"yellow","prevMsg":"Waiting for Elasticsearch"}
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:06Z","tags":["status","ui settings","error"],"pid":18,"state":"red","message":"Status changed from yellow to red - Elasticsearch plugin is red","prevState":"yellow","prevMsg":"Elasticsearch plugin is yellow"}
elasticsearch_1  | [2016-09-15 21:16:07,402][INFO ][node                     ] [logstash] initialized
elasticsearch_1  | [2016-09-15 21:16:07,403][INFO ][node                     ] [logstash] starting ...
elasticsearch_1  | [2016-09-15 21:16:07,535][INFO ][transport                ] [logstash] publish_address {127.0.0.1:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2016-09-15 21:16:07,542][INFO ][bootstrap                ] [logstash] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elasticsearch_1  | [2016-09-15 21:16:07,547][WARN ][bootstrap                ] [logstash] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupError: java.lang.RuntimeException: bootstrap checks failed
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:105)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:96)
elasticsearch_1  |      at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:54)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:68)
elasticsearch_1  | Caused by: java.lang.RuntimeException: bootstrap checks failed
elasticsearch_1  | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
elasticsearch_1  |      at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:132)
elasticsearch_1  |      at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:85)
elasticsearch_1  |      at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:65)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.validateNodeBeforeAcceptingRequests(Bootstrap.java:178)
elasticsearch_1  |      at org.elasticsearch.node.Node.start(Node.java:471)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:193)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:101)
elasticsearch_1  |      ... 6 more
elasticsearch_1  |      Suppressed: java.lang.IllegalStateException: max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
elasticsearch_1  |              at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
elasticsearch_1  |              at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
elasticsearch_1  |              at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
elasticsearch_1  |              at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
elasticsearch_1  |              at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
elasticsearch_1  |              at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
elasticsearch_1  |              at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
elasticsearch_1  |              at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
elasticsearch_1  |              at org.elasticsearch.bootstrap.BootstrapCheck.check(BootstrapCheck.java:133)
elasticsearch_1  |              ... 13 more
elasticsearch_1  | [2016-09-15 21:16:07,549][INFO ][node                     ] [logstash] stopping ...
elasticsearch_1  | [2016-09-15 21:16:07,745][INFO ][node                     ] [logstash] stopped
elasticsearch_1  | [2016-09-15 21:16:07,746][INFO ][node                     ] [logstash] closing ...
elasticsearch_1  | [2016-09-15 21:16:07,766][INFO ][node                     ] [logstash] closed
dockerelk5_elasticsearch_1 exited with code 1
kibana_1         | {"type":"log","@timestamp":"2016-09-15T21:16:09Z","tags":["status","plugin:elasticsearch@5.0.0-alpha5","error"],"pid":18,"state":"red","message":"Status changed from red to red - Service Unavailable","prevState":"red","prevMsg":"Unable to connect to Elasticsearch at http://elasticsearch:9200."}

**Comment by jmreicha** [comment]
Check [this issue](https://github.com/docker-library/elasticsearch/issues/98).

Basically you need to set max_map_count to be higher.  You can set it with something like `sysctl -w vm.max_map_count=262144`.
